# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class Test3333():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_3333(self):
        self.driver.get("https://www.runoob.com/try/try.php?filename=tryhtml5_draganddrop")
        self.driver.set_window_size(1680, 984)
        self.driver.find_element(By.CSS_SELECTOR, ".CodeMirror-line:nth-child(14)").click()
        self.driver.switch_to.frame(0)
        self.driver.find_element(By.ID, "drag1").click()
        dragged = self.driver.find_element(By.ID, "drag1")
        dropped = self.driver.find_element(By.ID, "div1")
        actions = ActionChains(self.driver)
        actions.drag_and_drop(dragged, dropped).perform()
