# Generated by Selenium IDE
import importlib

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities




class aaaa:
    def __init__(self, abcd):
        self.abcd = abcd

    def p(self):
        print(self.abcd)
        return self.abcd

x = aaaa('1234')
x.p()
print(x.__class__.__name__)


im = importlib.import_module('xuexi')

main = getattr(im,'main')
print(main)