# Generated by Django 3.1.7 on 2021-07-05 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试用例行为类型')),
                ('action_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试用例行为名称')),
                ('action', models.JSONField(blank=True, null=True, verbose_name='测试用例行为')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseCheckPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_point_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试用例验证点类型')),
                ('check_point_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试用例验证点名称')),
                ('check_point', models.JSONField(blank=True, null=True, verbose_name='测试用例验证点')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试用例数据类型')),
                ('data_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='测试用例数据名称')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='测试用例数据')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_id', models.CharField(max_length=32, null=True, unique=True, verbose_name='测试用例id')),
                ('test_case_name', models.CharField(max_length=128, null=True, unique=True, verbose_name='测试用例名称')),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_case_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='测试用例类型')),
                ('tc_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcase.testcaseaction', verbose_name='测试用例行为')),
                ('tc_check_list', models.ManyToManyField(blank=True, to='testcase.TestCaseCheckPoint', verbose_name='测试用例验证')),
                ('tc_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testcase.testcasedata', verbose_name='测试用例数据')),
                ('tc_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testcase.testcaseidentity', verbose_name='测试用例身份信息')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
