# Generated by Django 3.1.7 on 2021-07-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFlowS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='流程名')),
                ('status', models.CharField(blank=True, max_length=128, null=True, verbose_name='流程状态')),
                ('result_rule', models.JSONField(blank=True, null=True, verbose_name='流程业务结果规则')),
                ('result', models.CharField(blank=True, max_length=128, null=True, verbose_name='流程业务结果')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='流程业务数据')),
                ('step_list', models.JSONField(blank=True, null=True, verbose_name='流程步骤列表')),
            ],
        ),
    ]
